KS-15-3 Admin/User/Forum classes: write/read/delete msg
toto-neutrino1/KotlinSprint pull request #74
Opened 2023-07-28 15:31 UTC by toto-neutrino1

2023-07-29 19:56 UTC, ievetrov requested changes
вообще по ТЗ класс форум не упоминается вообще, но если он есть, можно перенести логику внутрь форума. чтобы не передавать мессаджи при каждом написании сообщения

2023-08-03 18:48 UTC, toto-neutrino1 commented
> вообще по ТЗ класс форум не упоминается вообще, но если он есть, можно перенести логику внутрь форума. чтобы не передавать мессаджи при каждом написании сообщения

Решил не добавлять всю логику внутрь класса Forum, т.к. это полностью ломает изначальное условие задачи - классы User и Admin пришлось бы удалить или существенно их преобразовать, что совсем не соответствовало бы условию задачи.

Ещё у меня вопрос - если бы я оставил класс Forum, прописав всю логику внутри него, было бы нужно, чтобы часть методов были доступны только админам, а обычные пользователи как минимум не могли ими пользоваться (а в идеале - не видели бы даже этих методов).
Вопрос - как сделать так, чтобы какие-то функции были доступны только определенному виду пользователей?

Как сделать так, чтобы саму функцию все пользователи видели, но воспользоваться могли только те, которые меня интересуют, я понимаю (ветвлением это легко отсекается).

Но как сделать так, чтобы какой-то метод был виден только определенной категории, а другие её и не видели? Кроме как созданием нескольких классов это можно как-то сделать?

2023-08-04 19:47 UTC, ievetrov requested changes

2023-08-07 11:37 UTC, toto-neutrino1 commented
> 

Задача, про которую я писал, следующая:
есть класс Forum, в котором хотелось бы реализовать логику задачи 15-3, то есть в нём есть 2 вида пользователей (обычные и админы), есть общий для всех пользователей функционал, но у админов есть в доступе дополнительные функции, недоступные обычным пользователям.
Хотелось всё сделать в одном классе Forum, чтобы не передавать каждый раз в качестве параметра во все методы параметр messages (набор всех сообщений является общим для всего форума, поэтому хотелось избавиться от передачи одного и того же неизменного аргумента во все функции).

Теперь по пунктам.

1) "А зачем? У нас же пользователи не занимаются написанием кода ))) То есть, не будет такой ситуации, где пользователи "увидят" какой-то метод. Твой код - это лишь модель реального мира. В реальном мире есть Админы и Пользователи. Если пользователи не могут что-то делать, не объявляй таких функций."

Да, про модель реального мира понимаю. Думаю, я перемудрил, и в целом схема решения с классом Forum не будет оптимальной, и лучше 2 независимых класса объявить и всё.

2) "Как сделать так, чтобы саму функцию все пользователи видели, но воспользоваться могли только те, которые меня интересуют, я понимаю (ветвлением это легко отсекается)." - я имею в виду следующее:
Если все методы и свойства прописать в одном классе Forum, то их априори увидят все виды пользователей (например, функцию deleteUser увидят и админы, и обычные пользователи). Но чтобы ей могли воспользоваться только админы, можно внутри функции deleteUser написать if (user in admins) { тело функции } - то есть увидят этот метод все, но пользоваться им смогут только админы.

3) "Думаю нет. Ты уже вводишь понятие "категория", "видимость". Можно сделать пользователя User() у которого есть поле role, и смотреть на него. Но задача не про это".

Понял, спасибо! То есть в рамках только одного класса Forum сделать то, что я описывал, проблематично, лучше разбить на 2 класса всю логику и всё.

2023-08-07 11:39 UTC, toto-neutrino1 commented on src/main/kotlin/lesson_15/lesson15_task3.kt
> +class Admin(admin: String) : User(admin) {
Логично, спасибо! Сейчас исправлю. 
Идея в таком наследовании была в том, что у админа есть дополнительные возможности по сравнению с обычным пользователем, поэтому их общие методы не придётся переопределять в обоих классах

2023-08-07 11:42 UTC, toto-neutrino1 commented
> > Вопрос - как сделать так, чтобы какие-то функции были доступны только определенному виду пользователей?
> 
> А зачем? У нас же пользователи не занимаются написанием кода ))) То есть, не будет такой ситуации, где пользователи "увидят" какой-то метод. Твой код - это лишь модель реального мира. В реальном мире есть Админы и Пользователи. Если пользователи не могут что-то делать, не объявляй таких функций.
> 
> > Как сделать так, чтобы саму функцию все пользователи видели, но воспользоваться могли только те, которые меня интересуют, я понимаю (ветвлением это легко отсекается).
> 
> Я не совсем понимаю какую задачу ты решаешь. Опиши конкретный пример
> 
> > Но как сделать так, чтобы какой-то метод был виден только определенной категории, а другие её и не видели? Кроме как созданием нескольких классов это можно как-то сделать?
> 
> Думаю нет. Ты уже вводишь понятие "категория", "видимость". Можно сделать пользователя User() у которого есть поле role, и смотреть на него. Но задача не про это


Задача, про которую я писал, следующая:
есть класс Forum, в котором хотелось бы реализовать логику задачи 15-3, то есть в нём есть 2 вида пользователей (обычные и админы), есть общий для всех пользователей функционал, но у админов есть в доступе дополнительные функции, недоступные обычным пользователям.
Хотелось всё сделать в одном классе Forum, чтобы не передавать каждый раз в качестве параметра во все методы параметр messages (набор всех сообщений является общим для всего форума, поэтому хотелось избавиться от передачи одного и того же неизменного аргумента во все функции).

Теперь по пунктам.

1) "А зачем? У нас же пользователи не занимаются написанием кода ))) То есть, не будет такой ситуации, где пользователи "увидят" какой-то метод. Твой код - это лишь модель реального мира. В реальном мире есть Админы и Пользователи. Если пользователи не могут что-то делать, не объявляй таких функций."

Да, про модель реального мира понимаю. Думаю, я перемудрил, и в целом схема решения с классом Forum не будет оптимальной, и лучше 2 независимых класса объявить и всё.

2) "Как сделать так, чтобы саму функцию все пользователи видели, но воспользоваться могли только те, которые меня интересуют, я понимаю (ветвлением это легко отсекается)." - я имею в виду следующее:
Если все методы и свойства прописать в одном классе Forum, то их априори увидят все виды пользователей (например, функцию deleteUser увидят и админы, и обычные пользователи). Но чтобы ей могли воспользоваться только админы, можно внутри функции deleteUser написать if (user in admins) { тело функции } - то есть увидят этот метод все, но пользоваться им смогут только админы.

3) "Думаю нет. Ты уже вводишь понятие "категория", "видимость". Можно сделать пользователя User() у которого есть поле role, и смотреть на него. Но задача не про это".

Понял, спасибо! То есть в рамках только одного класса Forum сделать то, что я описывал, проблематично, лучше разбить на 2 класса всю логику и всё.

2023-08-08 18:24 UTC, ievetrov requested changes
> Задача, про которую я писал, следующая:
> есть класс Forum, в котором хотелось бы реализовать логику задачи 15-3, то есть в нём есть 2 вида пользователей (обычные и админы), есть общий для всех пользователей функционал, но у админов есть в доступе дополнительные функции, недоступные обычным пользователям.
> Хотелось всё сделать в одном классе Forum, чтобы не передавать каждый раз в качестве параметра во все методы параметр messages (набор всех сообщений является общим для всего форума, поэтому хотелось избавиться от передачи одного и того же неизменного аргумента во все функции).

Я тебя понял, ты хотел в [5 задачу 11 урока](https://github.com/toto-neutrino1/KotlinSprint/pull/56) добавить функционал с разграничением прав доступа. 

Давай сделаем! 
Тогда возвращай форум )
1. У форума будут методы `deleteMessage(userId: Int, messageId: Int)` и `deleteUser(userId: Int, deletingUserId: Int)`. Где userId - это id пользователя от имени которого мы пытаемся выполнить операцию. Внутри метода проводится проверка, является ли пользователь админом, например - ищется в списке пользователей User с указанным id и проверяется класс ( user is AdminUser)
2. Сообщения и пользователи хранятся также в своих списках
3. Если пользователь не может удалять, метод возвращает false, при удалении - true

2023-08-11 11:39 UTC, ievetrov requested changes
Давай улучшать, пока что плохо структурировано

2023-08-12 19:53 UTC, toto-neutrino1 commented on src/main/kotlin/lesson_15/lesson15_task3.kt
> +    forum.users.addAll(admins)
Сделал, единственное, в моей реализации метод ничего не возвращает, а просто добавляет пользователя в список users (или не добавляет, если добавление невозможно)

2023-08-12 19:55 UTC, toto-neutrino1 commented on src/main/kotlin/lesson_15/lesson15_task3.kt
> +        return if (userId in 1..users.size &&
Действительно, не учёл этого, спасибо! 
Исправил

2023-08-13 19:59 UTC, ievetrov requested changes
Предлагаю еще немного доработать )

2023-08-15 17:33 UTC, danelyan approved these changes
Да, теперь отлично.
Я как злой ревьювер докопался бы что lastUserId у тебя не хранит last User Id, скорее nextUserId. Но это не критично.

Главное что появилось понимание, как проектировать подобные классы

2023-08-15 20:53 UTC, toto-neutrino1 commented
> Да, теперь отлично. Я как злой ревьювер докопался бы что lastUserId у тебя не хранит last User Id, скорее nextUserId. Но это не критично.
> 
> Главное что появилось понимание, как проектировать подобные классы

Понял, принял )
Спасибо!

2023-08-15 21:21 UTC, merged